"resource/OptionsSubVideoAdvancedDlg.res"
{
	"OptionsSubVideoAdvancedDlg"
	{
		"ControlName"		"COptionsSubVideoAdvancedDlg"
		"fieldName"		"OptionsSubVideoAdvancedDlg"
		"xpos"		"559"
		"ypos"		"250"
		"wide"		"482"
		"tall"		"335"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"settitlebarvisible"		"1"
		"title"		"#GameUI_VideoAdvanced_Title"
	}
	"frame_topGrip"
	{
		"ControlName"		"Panel"
		"fieldName"		"frame_topGrip"
		"xpos"		"8"
		"ypos"		"0"
		"wide"		"466"
		"tall"		"5"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"frame_bottomGrip"
	{
		"ControlName"		"Panel"
		"fieldName"		"frame_bottomGrip"
		"xpos"		"8"
		"ypos"		"330"
		"wide"		"456"
		"tall"		"5"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"frame_leftGrip"
	{
		"ControlName"		"Panel"
		"fieldName"		"frame_leftGrip"
		"xpos"		"0"
		"ypos"		"8"
		"wide"		"5"
		"tall"		"319"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"frame_rightGrip"
	{
		"ControlName"		"Panel"
		"fieldName"		"frame_rightGrip"
		"xpos"		"477"
		"ypos"		"8"
		"wide"		"5"
		"tall"		"309"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"frame_tlGrip"
	{
		"ControlName"		"Panel"
		"fieldName"		"frame_tlGrip"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"8"
		"tall"		"8"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"frame_trGrip"
	{
		"ControlName"		"Panel"
		"fieldName"		"frame_trGrip"
		"xpos"		"474"
		"ypos"		"0"
		"wide"		"8"
		"tall"		"8"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"frame_blGrip"
	{
		"ControlName"		"Panel"
		"fieldName"		"frame_blGrip"
		"xpos"		"0"
		"ypos"		"327"
		"wide"		"8"
		"tall"		"8"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"frame_brGrip"
	{
		"ControlName"		"Panel"
		"fieldName"		"frame_brGrip"
		"xpos"		"464"
		"ypos"		"317"
		"wide"		"18"
		"tall"		"18"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"frame_caption"
	{
		"ControlName"		"Panel"
		"fieldName"		"frame_caption"
		"xpos"		"0"
		"ypos"		"0"
		"zpos"		"-1"
		"wide"		"472"
		"tall"		"23"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"frame_minimize"
	{
		"ControlName"		"Button"
		"fieldName"		"frame_minimize"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"18"
		"tall"		"18"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"0"
		"textAlignment"		"north-west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"auto_wide_tocontents"		"0"
		"textinsetx"		"2"
		"textinsety"		"1"
		"default"		"0"
	}
	"frame_maximize"
	{
		"ControlName"		"Button"
		"fieldName"		"frame_maximize"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"18"
		"tall"		"18"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"1"
		"textAlignment"		"north-west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"auto_wide_tocontents"		"0"
		"textinsetx"		"2"
		"textinsety"		"1"
		"default"		"0"
	}
	"frame_mintosystray"
	{
		"ControlName"		"Button"
		"fieldName"		"frame_mintosystray"
		"xpos"		"0"
		"ypos"		"0"
		"wide"		"18"
		"tall"		"18"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"o"
		"textAlignment"		"north-west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"auto_wide_tocontents"		"0"
		"textinsetx"		"2"
		"textinsety"		"1"
		"command"		"MinimizeToSysTray"
		"default"		"0"
	}
	"frame_close"
	{
		"ControlName"		"Button"
		"fieldName"		"frame_close"
		"xpos"		"457"
		"ypos"		"8"
		"zpos"		"1"
		"wide"		"18"
		"tall"		"18"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"r"
		"textAlignment"		"north-west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"auto_wide_tocontents"		"0"
		"textinsetx"		"2"
		"textinsety"		"1"
		"default"		"0"
	}
	"frame_menu"
	{
		"ControlName"		"FrameSystemButton"
		"fieldName"		"frame_menu"
		"xpos"		"7"
		"ypos"		"8"
		"wide"		"18"
		"tall"		"18"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"auto_wide_tocontents"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
		"default"		"0"
	}
	"ModelDetail"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"ModelDetail"
		"xpos"		"22"
		"ypos"		"58"
		"wide"		"132"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"1"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"TextureDetail"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"TextureDetail"
		"xpos"		"176"
		"ypos"		"58"
		"wide"		"132"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"2"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"AntialiasingMode"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"AntialiasingMode"
		"xpos"		"22"
		"ypos"		"196"
		"wide"		"132"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"7"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"ShadowDetail"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"ShadowDetail"
		"xpos"		"22"
		"ypos"		"118"
		"wide"		"132"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"5"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"WaterDetail"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"WaterDetail"
		"xpos"		"330"
		"ypos"		"58"
		"wide"		"132"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"4"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"VSync"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"VSync"
		"xpos"		"330"
		"ypos"		"196"
		"wide"		"132"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"9"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"Multicore"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"Multicore"
		"xpos"		"330"
		"ypos"		"258"
		"wide"		"132"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"10"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"MotionBlur"
	{
		"ControlName"		"ComboBox"
		"fieldName"		"MotionBlur"
		"xpos"		"22"
		"ypos"		"258"
		"wide"		"132"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"10"
		"textHidden"		"0"
		"editable"		"0"
		"maxchars"		"-1"
		"NumericInputOnly"		"0"
		"unicode"		"0"
	}
	"Motion Blur Label"
	{
		"ControlName"		"Label"
		"fieldName"		"Motion Blur Label"
		"xpos"		"22"
		"ypos"		"232"
		"wide"		"138"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_MotionBlur"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"auto_wide_tocontents"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
	}
	"Button1"
	{
		"ControlName"		"Button"
		"fieldName"		"Button1"
		"xpos"		"290"
		"ypos"		"300"
		"wide"		"80"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"16"
		"labelText"		"#GameUI_OK"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"auto_wide_tocontents"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"command"		"OK"
		"default"		"0"
		"selected"		"0"
	}
	"Button2"
	{
		"ControlName"		"Button"
		"fieldName"		"Button2"
		"xpos"		"382"
		"ypos"		"300"
		"wide"		"80"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"17"
		"labelText"		"#GameUI_Cancel"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"auto_wide_tocontents"		"0"
		"textinsetx"		"6"
		"textinsety"		"0"
		"command"		"Close"
		"default"		"1"
		"selected"		"0"
	}
	"Label3"
	{
		"ControlName"		"Label"
		"fieldName"		"Label3"
		"xpos"		"22"
		"ypos"		"34"
		"wide"		"112"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Model_Detail"
		"textAlignment"		"west"
		"associate"		"ModelDetail"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"auto_wide_tocontents"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
	}
	"Label4"
	{
		"ControlName"		"Label"
		"fieldName"		"Label4"
		"xpos"		"175"
		"ypos"		"33"
		"wide"		"124"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Texture_Detail"
		"textAlignment"		"west"
		"associate"		"TextureDetail"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"auto_wide_tocontents"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
	}
	"Label5"
	{
		"ControlName"		"Label"
		"fieldName"		"Label5"
		"xpos"		"22"
		"ypos"		"172"
		"wide"		"156"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Antialiasing_Mode"
		"textAlignment"		"west"
		"associate"		"AntialiasingMode"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"auto_wide_tocontents"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
	}
	"Label7"
	{
		"ControlName"		"Label"
		"fieldName"		"Label7"
		"xpos"		"330"
		"ypos"		"34"
		"wide"		"132"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Water_Detail"
		"textAlignment"		"west"
		"associate"		"WaterDetail"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"auto_wide_tocontents"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
	}
	"Label8"
	{
		"ControlName"		"Label"
		"fieldName"		"Label8"
		"xpos"		"22"
		"ypos"		"94"
		"wide"		"132"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Shadow_Detail"
		"textAlignment"		"west"
		"associate"		"ShadowDetail"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"auto_wide_tocontents"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
	}
	"Label10"
	{
		"ControlName"		"Label"
		"fieldName"		"Label10"
		"xpos"		"330"
		"ypos"		"172"
		"wide"		"154"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_Wait_For_VSync"
		"textAlignment"		"west"
		"associate"		"VSync"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"auto_wide_tocontents"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
	}
	"Divider2"
	{
		"ControlName"		"Divider"
		"fieldName"		"Divider2"
		"xpos"		"22"
		"ypos"		"160"
		"wide"		"438"
		"tall"		"2"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"FovSlider"
	{
		"ControlName"		"CCvarSlider"
		"fieldName"		"FovSlider"
		"xpos"		"176"
		"ypos"		"192"
		"wide"		"140"
		"tall"		"50"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"11"
		"leftText"		"75.00"
		"rightText"		"90.00"
		"minvalue"		"75.000000"
		"maxvalue"		"90.000000"
		"cvar_name"		"fov_desired"
		"allowoutofrange"		"0"
	}
	"FOVLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"FOVLabel"
		"xpos"		"176"
		"ypos"		"172"
		"wide"		"168"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_FOV"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"auto_wide_tocontents"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
	}
	"MulticoreLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"MulticoreLabel"
		"xpos"		"330"
		"ypos"		"232"
		"wide"		"168"
		"tall"		"24"
		"AutoResize"		"0"
		"PinCorner"		"0"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#GameUI_MulticoreRendering"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
		"centerwrap"		"0"
		"auto_wide_tocontents"		"0"
		"textinsetx"		"0"
		"textinsety"		"0"
	}
}
